name: CI-CD
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: SFTP Deploy
        uses: hengkx/ssh-deploy@v1.0.1
        env:
          HOST: 206.54.191.10
          USERNAME: root
          PASSWORD: x6QRcNf4YPVj1i2g35
          PORT: 22
          TARGET: /var/www/api
